influxdb:
  url: "http://localhost:3000" # InfluxDB 서버 URL
  username: "user" # 사용자 이름
  password: "password" # 비밀번호
  database: "mydatabase" # 데이터베이스 이름
  retentionPolicy: "autogen" # 보존 정책
meraki:
  organizationId: "1234567890" # 메라키 조직 ID
  apiKey: "1234567890" # 메라키 API 키
  networkId: "1234567890" # 메라키 네트워크 ID